[build]
  publish = "public/"
  command = "node ./node_modules/sass/sass.js src/assets/sass:./src/assets/css && ELEVENTY_ENV=PROD node ./node_modules/@11ty/eleventy/cmd.cjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--ignore-scripts"
